### ISSUE TITLE
Weird watch

### ISSUE THREAD

**Issue by Shuunen** [saurabhdaware/typescript-run#3]
Hi, thanks for your package :)

I have some weird behaviours : 

- `ts-run src --watch` works
- `ts-run src --watch foobar` does not work and show `❌  unknown or unexpected option: --watch`
- `ts-run src -w foobar` works

Any ideas ?

**Comment by Shuunen** [comment]
Yes I tought that `ts-run src --watch foobar` & `ts-run src -w foobar` would be the same command because `-w` is an alias of `--watch`

**Comment by saurabhdaware** [comment]
Strange. It seems to be working for me. Is it possible for you to reproduce this on stackblitz?

**Comment by Shuunen** [comment]
that's embarassing 😟 

- work fine on Stackblitz
- work fine on my desktop Win11 x64 node 16
- still not working on my laptop Win 11 x64 node 16

You can close the issue, the issue is not related to your lib, sorry 😝

**Comment by saurabhdaware** [comment]
oh weird 🤔 If you're interested you can try adding console logs in the `node_modules/typescript-run` code and see where it is breaking. That might help in debugging and fixing it.
